
name: photo_guide_ai
description: A smart Flutter camera guide app.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+3
  path_provider: ^2.1.2
  path: ^1.9.0

flutter:
  uses-material-design: true
